run:
  tests: true
  modules-download-mode: vendor
  skip-dirs:
  - vendor
  - pkg/rgbmatrix-rpi
  timeout: 5m
linters:
  disable-all: true
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - durationcheck
  - errcheck
  - exportloopref
  - goconst
  - gofumpt
  - goimports
  - golint
  - gosimple
  - govet
  - importas
  - ineffassign
  - misspell
  - nilerr
  - nakedret
  - staticcheck
  - structcheck
  - tparallel
  - unconvert
  - unused
  - unparam
  - varcheck
  - whitespace
linters-settings:
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/robbydyer/sports
issues:
  exclude-use-default: false
  exclude:
  - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
  - 'shadow: declaration of "err" shadows declaration at line (\d+)'
