run:
  # Until https://github.com/golangci/golangci-lint/issues/2649
  go: 1.20
  tests: true
  modules-download-mode: vendor
  timeout: 5m
linters:
  disable-all: true
  enable:
  - asciicheck
  - bodyclose
  - contextcheck
  - durationcheck
  - errcheck
  - errorlint
  - exportloopref
  - importas
  - ineffassign
  - gofumpt
  - goimports
  - gosimple
  - govet
  - misspell
  - nakedret
  - nilerr
  - noctx
  - nonamedreturns
  - nosprintfhostport
  - paralleltest
  - predeclared
  - promlinter
  - revive
  - sqlclosecheck
  - staticcheck
  - tparallel
  - unconvert
  - unused
  - unparam
  - whitespace
linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/robbydyer/sports
  revive:
    rules:
    - name: exported
      disabled: true
issues:
  exclude-use-default: false
  exclude-dirs:
  - vendor
  - internal/rgbmatrix-rpi
  - internal/proto
  exclude:
  - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
  - 'shadow: declaration of "err" shadows declaration at line (\d+)'
