// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sportboard

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SportClient is the client API for Sport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SportClient interface {
	SetStatus(ctx context.Context, in *SetStatusReq, opts ...grpc.CallOption) (*empty.Empty, error)
	GetStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResp, error)
}

type sportClient struct {
	cc grpc.ClientConnInterface
}

func NewSportClient(cc grpc.ClientConnInterface) SportClient {
	return &sportClient{cc}
}

func (c *sportClient) SetStatus(ctx context.Context, in *SetStatusReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/sport.v1.Sport/SetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sportClient) GetStatus(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResp, error) {
	out := new(StatusResp)
	err := c.cc.Invoke(ctx, "/sport.v1.Sport/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SportServer is the server API for Sport service.
// All implementations must embed UnimplementedSportServer
// for forward compatibility
type SportServer interface {
	SetStatus(context.Context, *SetStatusReq) (*empty.Empty, error)
	GetStatus(context.Context, *empty.Empty) (*StatusResp, error)
	mustEmbedUnimplementedSportServer()
}

// UnimplementedSportServer must be embedded to have forward compatible implementations.
type UnimplementedSportServer struct {
}

func (UnimplementedSportServer) SetStatus(context.Context, *SetStatusReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedSportServer) GetStatus(context.Context, *empty.Empty) (*StatusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedSportServer) mustEmbedUnimplementedSportServer() {}

// UnsafeSportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SportServer will
// result in compilation errors.
type UnsafeSportServer interface {
	mustEmbedUnimplementedSportServer()
}

func RegisterSportServer(s grpc.ServiceRegistrar, srv SportServer) {
	s.RegisterService(&Sport_ServiceDesc, srv)
}

func _Sport_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sport.v1.Sport/SetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportServer).SetStatus(ctx, req.(*SetStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sport_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sport.v1.Sport/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportServer).GetStatus(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Sport_ServiceDesc is the grpc.ServiceDesc for Sport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sport.v1.Sport",
	HandlerType: (*SportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetStatus",
			Handler:    _Sport_SetStatus_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _Sport_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sportboard/sportboard.proto",
}
