package mlb

// ALL contains all of the teams in the league
var ALL = []string{ARI, ATL, BAL, BOS, CHC, CIN, CLE, COL, CWS, DET, HOU, KC, LAA, LAD, MIA, MIL, MIN, NYM, NYY, OAK, PHI, PIT, SD, SEA, SF, STL, TB, TEX, TOR, WSH}

const (
	// ARI ...
	ARI = "ARI"
	// ATL ...
	ATL = "ATL"
	// BAL ...
	BAL = "BAL"
	// BOS ...
	BOS = "BOS"
	// CHC ...
	CHC = "CHC"
	// CIN ...
	CIN = "CIN"
	// CLE ...
	CLE = "CLE"
	// COL ...
	COL = "COL"
	// CWS ...
	CWS = "CWS"
	// DET ...
	DET = "DET"
	// HOU ...
	HOU = "HOU"
	// KC ...
	KC = "KC"
	// LAA ...
	LAA = "LAA"
	// LAD ...
	LAD = "LAD"
	// MIA ...
	MIA = "MIA"
	// MIL ...
	MIL = "MIL"
	// MIN ...
	MIN = "MIN"
	// NYM ...
	NYM = "NYM"
	// NYY ...
	NYY = "NYY"
	// OAK ...
	OAK = "OAK"
	// PHI ...
	PHI = "PHI"
	// PIT ...
	PIT = "PIT"
	// SD ...
	SD = "SD"
	// SEA ...
	SEA = "SEA"
	// SF ...
	SF = "SF"
	// STL ...
	STL = "STL"
	// TB ...
	TB = "TB"
	// TEX ...
	TEX = "TEX"
	// TOR ...
	TOR = "TOR"
	// WSH ...
	WSH = "WSH"
)
