#!/bin/bash
set -euo pipefail

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

source "${ROOT}/script/common"

set -x
cd "${ROOT}"

dockerlogin

docker --config="${DOCKERCONF}" buildx create --use --name=build --node=build

linter=$(latestlinter)

if [ "$(docker images -q ${linter})" = "" ]; then
  echo "==> Building linter image"
  docker --config="${DOCKERCONF}" buildx build -t "${linter}" \
    --builder=build \
    -f Dockerfile.lint \
    --platform=linux/amd64,linux/arm64/v8 \
    --push \
    .
fi
