#!/bin/bash
# This script is used to build the docker image that is used to run builds.
set -euo pipefail

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

source "${ROOT}/script/common"

set -x
cd "${ROOT}"
img=$(latestpibuilder)

dockerlogin

docker --config="${DOCKERCONF}" buildx create --use --name=build --node=build

if [ "$(docker images -q ${img})" = "" ]; then
  echo "==> Building pibuilder image"
  docker --config="${DOCKERCONF}" buildx build -t "${img}" -t robbydyer/pibuilder:latest \
    --builder=build \
    -f Dockerfile.pibuilder \
    --platform=linux/amd64,linux/arm64/v8 \
    --push \
    .
fi
