#!/bin/bash
set -euo pipefail

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

source "${ROOT}/script/build.pibuilder"

set -x
cd "${ROOT}"
img=$(latestpibuilder)

docker buildx create --use --name=build --node=build

if [ "$(docker images -q ${img})" = "" ]; then
  echo "==> Building pibuilder image"
  docker buildx build -t "${img}" -t robbydyer/pibuilder:latest \
    --builder=build \
    -f Dockerfile.pibuilder \
    --platform=linux/amd64,linux/arm64/v8 \
    --push \
    .
fi

# Linter
linter=$(latestlinter)

if [ "$(docker images -q ${linter})" = "" ]; then
  echo "==> Building linter image"
  docker buildx build -t robbydyer/rgbmatrixlint:latest \
    --builder=build \
    -f Dockerfile.lint \
    --platform=linux/amd64,linux/arm64/v8 \
    --push \
    .
fi
