#!/bin/bash
set -euo pipefail
set -x

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"
cd "${ROOT}"
IN_DOCKER="${IN_DOCKER:-no}"
SUFFIX="build"

if [ "${IN_DOCKER}" = "no" ]; then
  if ! uname -a | grep raspberry &> /dev/null; then
    source "${ROOT}/script/common"
    pibuilder=$(latestpibuilder)

    exec docker run -t --rm \
      -e IN_DOCKER=yes \
      -v "${ROOT}":/src \
      -w /src \
      ${pibuilder} \
      /src/script/$(basename $0)
  fi
fi

# Inside docker
ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

export CGO_ENABLED=1
export GOCACHE=/src/.cache

if [ ! -d "${ROOT}/internal/rgbmatrix-rpi/lib/rpi-rgb-led-matrix" ]; then
  if [ -d "${ROOT}/internal/rgmatrix-rpi/lib/rpi-rgb-led-matrix.${SUFFIX}" ]; then
    mv "${ROOT}/internal/rgbmatrix-rpi/lib/rpi-rgb-led-matrix.${SUFFIX}" "${ROOT}/internal/rgbmatrix-rpi/lib/rpi-rgb-led-matrix"
  else
    cp -r "${ROOT}/internal/rgbmatrix-rpi/lib/rpi-rgb-led-matrix.BASE" "${ROOT}/internal/rgbmatrix-rpi/lib/rpi-rgb-led-matrix"
  fi
fi

if [ ! -f "${ROOT}/internal/rgbmatrix-rpi/lib/rpi-rgb-led-matrix/lib/librgbmatrix.so.1" ]; then
  cd "${ROOT}/internal/rgbmatrix-rpi/lib/rpi-rgb-led-matrix"
  make
fi

trap "mv ${ROOT}/internal/rgbmatrix-rpi/lib/rpi-rgb-led-matrix ${ROOT}/internal/rgbmatrix-rpi/lib/rpi-rgb-led-matrix.${SUFFIX} || true" EXIT

cd "${ROOT}"
go build -o sportsmatrix.${SUFFIX}  ./cmd/sportsmatrix
