#!/bin/bash
set -euo pipefail

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"
IN_DOCKER="${IN_DOCKER:-no}"
IMG="robbydyer/rgbmatrixlint:latest"

MOUNTOPTION=""
fix=""
if [ "$(uname -s)" = "Darwin" ]; then
  MOUNTOPTION=":delegated"
  fix="--fix"
fi

set -x
docker run -t --rm \
  -e IN_DOCKER=yes \
  -u $(id -u):$(id -g) \
  -v "${ROOT}":/src${MOUNTOPTION} \
  -w /src \
  -e GOCACHE="/src/.cache" \
  -e GOLANGCI_LINT_CACHE="/src/.cache" \
  -e GO111MODULE=on \
  -e CGO_ENABLED=1 \
  "${IMG}" \
  bash -cex "golangci-lint run --verbose ${fix}"
