#!/bin/bash
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
cd "${ROOT}"

img="znly/protoc:0.4.0"

for f in `echo proto/*`; do
  gof="$(echo $f | cut -f1 -d.)"

  set -x
  docker run --rm \
    -u $(id -u):$(id -g) \
    -v ${ROOT}:/src:delegated \
    -w /src \
    $img \
    --proto_path=/src/proto --go_out=/src/internal/proto --twirp_out=/src/internal/proto /src/${f}
    #protoc -I ./proto --go_out=plugins=grpc:internal/${gof} ${f}
done
