#!/bin/bash
set -euo pipefail

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"
set -x
VERSION="${VERSION/v/}"

"${ROOT}/script/web-build"

BUILDARCH=aarch64 DEB_BUILD=yes VERSION="${VERSION}" "${ROOT}/script/build" &
BUILDARCH=armv7l DEB_BUILD=yes VERSION="${VERSION}" "${ROOT}/script/build" &
BUILDARCH=armv6l DEB_BUILD=yes VERSION="${VERSION}" "${ROOT}/script/build" &

wait
