#!/bin/bash
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
cd "${ROOT}"
IN_DOCKER="${IN_DOCKER:-no}"

if [ "${IN_DOCKER}" = "no" ]; then
  pkger -o ./cmd/sportsmatrix
  if ! docker images | grep pibuilder &> /dev/null; then
    docker buildx build -f Dockerfile.builder -t pibuilder .
  fi

  exec docker run -it --rm \
    -e IN_DOCKER=yes \
    -v "${ROOT}":/src \
    -w /src \
    pibuilder \
    /src/script/shell
fi

# Inside docker

export CGO_ENABLED=0
export GO111MODULE=on
export GOCACHE=/src/.cache
export GOOS=linux
export GOARCH=arm
export GOARM=6
export CC=arm-linux-gnueabihf-gcc
export CXX=arm-linux-gnueabihf-g++

set -x
cp -r ~/go/src/github.com/robbydyer/rgbmatrix-rpi/lib /src/vendor/github.com/robbydyer/rgbmatrix-rpi/
cd /src/vendor/github.com/robbydyer/rgbmatrix-rpi/lib/rpi-rgb-led-matrix
make
cd /src/vendor/github.com/robbydyer/rgbmatrix-rpi
rm -rf examples || true
go install -v ./...

cd /src
bash
