#!/bin/bash
set -euo pipefail

set -x
ROOT=$(git rev-parse --show-toplevel)

source "${ROOT}/script/build.pibuilder"
pibuilder=$(latestpibuilder)

docker run -t --rm \
  -e CGO_ENABLED=1 \
  -e GOCACHE=/src/.cache \
  -v "${ROOT}":/src \
  -w /src \
  ${pibuilder} \
  bash -cex "go test -v ./..."
