#!/bin/bash
set -euo pipefail


ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"

rm -rf "${ROOT}/internal/sportsmatrix/assets/web"

cd "${ROOT}/web"

npm run build
