#!/bin/bash
set -euo pipefail
set -x

ROOT="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd ))"
cd "${ROOT}"
source script/common
IN_DOCKER="${IN_DOCKER:-no}"
DO_INSTALL="${DO_INSTALL:-yes}"

BUILDARCH="${BUILDARCH:-$(uname -m)}"

img=$(latestpibuilder ${BUILDARCH})

if [ "${IN_DOCKER}" = "no" ]; then
  docker run -t --rm \
    -e IN_DOCKER=yes \
    -e DO_INSTALL="${DO_INSTALL}" \
    -v "${ROOT}":/app \
    -w /app \
    ${img} \
    /app/script/$(basename $0)

  exit
fi

# Everything below is inside docker
. ~/.bashrc
cd /app/web

if [ "${DO_INSTALL}" = "yes" ]; then
  nvm install
  npm install
fi
npm run build
[ ! -d /app/internal/sportsmatrix/assets ] && mkdir -p /app/internal/sportsmatrix/assets
[ -d /app/internal/sportsmatrix/assets/web ] && rm -rf /app/internal/sportsmatrix/assets/web
mv /app/web/build /app/internal/sportsmatrix/assets/web
