name: Beta Release
on:
  push:
    tags:
    - 'v*beta*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2.0.0
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Set env
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Lint
      run: ./script/lint

    - name: Test
      run: ./script/test

    - name: Build
      run: ./script/release-all

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.deb"
        generateReleaseNotes: true
        prerelease: true
