name: Build Linter Image
on: 
  pull_request:
    paths:
    - Dockerfile.lint

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: get sha256
      id: sha
      run: echo "sha=$(sha256sum Dockerfile.lint | awk '{print $1}')" >> $GITHUB_OUTPUT

    - name: build linter
      uses: docker/build-push-action@v4
      with:
        push: true
        file: Dockerfile.lint
        tags:  robbydyer/rgbmatrixlint:${{steps.sha.outputs.sha}}
        platforms: linux/amd64,linux/arm64/v8
