name: Build Docker Images
on: 
  pull_request:
    paths:
    - Dockerfile.pibuilder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: get sha256
      id: sha
      run: echo "sha=$(sha256sum Dockerfile.pibuilder | awk '{print $1}')" >> $GITHUB_OUTPUT

    - name: arm64
      uses: docker/build-push-action@v4
      with:
        push: true
        file: Dockerfile.pibuilder
        tags:  robbydyer/pibuilder-aarch64:${{steps.sha.outputs.sha}}
        build-args: |
          BASE=multiarch/debian-debootstrap:arm64-bullseye-slim
        platforms: linux/amd64,linux/arm64/v8

    - name: armv7l
      uses: docker/build-push-action@v4
      with:
        push: true
        file: Dockerfile.pibuilder
        tags:  robbydyer/pibuilder-armv7l:${{steps.sha.outputs.sha}}
        build-args: |
          BASE=multiarch/debian-debootstrap:armhf-buster-slim
        platforms: linux/amd64,linux/arm64/v8

    - name: amd64
      uses: docker/build-push-action@v4
      with:
        push: true
        file: Dockerfile.pibuilder
        tags:  robbydyer/pibuilder-amd64:${{steps.sha.outputs.sha}}
        build-args: |
          BASE=multiarch/debian-debootstrap:amd64-bullseye
        platforms: linux/amd64,linux/arm64/v8