name: Build Docker Images
on: 
  pull_request:
    paths:
    - Dockerfile.pibuilder
    - .github/workflows/dockerbuild.yml

jobs:
  build:
    strategy:
      matrix:
        arch:
        - aarch64
        - armv7l
        - amd64
        os:
        - trixie
        - bullseye
        - bookworm
        include:
        - arch: aarch64
          base: arm64
        - arch: armv7l
          base: armhf
        - arch: amd64
          base: amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3.5.0
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: get sha256
      id: sha
      run: echo "sha=$(sha256sum Dockerfile.pibuilder | awk '{print $1}')" >> $GITHUB_OUTPUT

    - name: Build ${{matrix.arch}}
      uses: docker/build-push-action@v6
      with:
        push: true
        file: Dockerfile.pibuilder
        tags:  robbydyer/pibuilder-${{matrix.arch}}-${{matrix.os}}:${{steps.sha.outputs.sha}}
        build-args: |
          BASE=robbydyer/debian-debootstrap:${{matrix.base}}-${{matrix.os}}-slim
        platforms: linux/amd64,linux/arm64/v8